level: info

redis:
  username: default
  master_name: mymaster
  addresses:
    - redis.redis.svc.cluster.local:26379
  database: 0
  sentinel: true

mongo:
  database: viders

rtmp:
  bind: 0.0.0.0:1935

  ingest:
    url: ingest.viders.svc.cluster.local:1935

  transcoder:
    url: transcoder.viders.svc.cluster.local:1935

  muxer:
    url: muxer.viders.svc.cluster.local:1935

pod:
  advertise_port: 80

monitoring:
  enabled: true
  bind: :9100

health:
  enabled: true
  bind: :9101
