name: Build Muxer

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build Muxer
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: recursive

      - name: Log into Harbor Registry
        uses: docker/login-action@v1
        with:
          registry: harbor.komodohype.dev
          username: robot$deploy
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: setup docker context for buildx
        id: buildx-context
        run: |
          docker context create builders

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
          endpoint: builders

      - name: Build Image
        id: build_step
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            "BUILDER=${{ github.actor }}"
            "VERSION=${{ github.sha }}"
          tags: |
            harbor.komodohype.dev/viders/muxer:${{ github.sha }}
            harbor.komodohype.dev/viders/muxer:latest

  deploy:
    name: Deploy (Production)
    runs-on: ubuntu-latest
    needs: # Run this after build
      - build

    steps:
      # Checkout repository
      - uses: actions/checkout@v2

      # Deploy to k8s
      - name: Install kubectl&
        uses: azure/setup-kubectl@v3.0

      - name: Apply Deployment & Rollout
        env:
          KUBE_CONFIG_DATA: ${{ secrets.VIDERS_AUTODEPLOY }}
          KUBE_RESOURCE: deploy
          KUBE_NAMESPACE: viders
          KUBE_IMAGE_PATCH: >-
            [
              { "op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "harbor.komodohype.dev/viders/muxer:${{ github.sha }}" }
            ]
        run: |
          mkdir -p ~/.kube
          (echo $KUBE_CONFIG_DATA | base64 -d) >> ~/.kube/config
          kubectl config use-context autodeploy@Viders

          kubectl patch -n $KUBE_NAMESPACE $KUBE_RESOURCE muxer --type="json" -p="$KUBE_IMAGE_PATCH"
